vagrant_hostname: local.justice8.doj.gov
vagrant_machine_name: justicegov8

drupal_build_composer_project: false
drupal_build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"

drupal_install_site: false

# MySQL databases and users.
mysql_databases:
  - name: "drupal"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: "migration"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "drupal"
    host: "%"
    password: "drupal"
    priv: "drupal.*:ALL"
  - name: "migration"
    host: "%"
    password: "migration"
    priv: "migration.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  # - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+
